### ISSUE TITLE
ランキング画面のGeekLink Activitiesで同じ人が2回表示されている

### ISSUE THREAD

**Issue by na2kera** [kou7306/GeekLink_frontend#180]
![スクリーンショット 2024-10-09 22 05 53](https://github.com/user-attachments/assets/60603ce5-acb4-4cf6-bb64-fe2ecbf90993)
他のランキングは大丈夫そう

**Comment by kappy0713** [comment]
ここはSupabaseで以前のデータが残っているのが原因ですね～
バッチ処理を修正すればよさそう？
