### ISSUE TITLE
test1@gmail.com以外のユーザーでマイページの編集ができない

### ISSUE THREAD

**Issue by na2kera** [kou7306/GeekLink_frontend#184]
![スクリーンショット 2024-10-09 22 12 21](https://github.com/user-attachments/assets/a36da435-8f5c-4edb-b82f-a1d8025400e2)

**Comment by kou7306** [comment]
Nullの処理

**Comment by kappy0713** [comment]
usersのimage_urlがNULLだと編集できない
初期値をEMPTYにするかNULLでも処理できるようにする

**Comment by kappy0713** [comment]
初期値をEMPTYに変更したので今後ユーザーを追加する際は問題ないかと。
現在のユーザーはimage_urlをNULLからEMPTYに変更する必要があります。
動作確認したらクローズします。

**Comment by kappy0713** [comment]
動作確認ができたためクローズします。
image_urlのデフォルト値はEMPTYに変更したので以後同様のエラーが発生することはないと思います。
