### ISSUE TITLE
ログアウトボタンを作る

### ISSUE THREAD

**Issue by na2kera** [kou7306/GeekLink_frontend#226]
現状ヘッダーにあったログアウトボタンがないので作る。
マイページ？

**Comment by na2kera** [comment]
<SignOutButton />

↑このコンポーネントを配置するだけ

**Comment by na2kera** [comment]
ホバーしたらサインアウト

**Comment by kou7306** [comment]
ヘッダーをユーザーアイコンにして、ホバーしたらサインアウトとマイページに飛べるボタンが出てくる
